# Generated by Django 5.2.3 on 2025-07-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_text', models.TextField()),
                ('vision_text', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mission & Vision',
                'verbose_name_plural': 'Mission & Vision',
            },
        ),
        migrations.CreateModel(
            name='OfficialMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Dean ACR', 'Dean ACR'), ('Director', 'Director'), ('Chairman', 'Chairman')], max_length=50, unique=True)),
                ('profile_picture', models.ImageField(upload_to='official_pics/')),
                ('message_title', models.CharField(blank=True, max_length=255, null=True)),
                ('message_content', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Order in which messages appear (lower number first)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Official Message',
                'verbose_name_plural': 'Official Messages',
                'ordering': ['order', 'role'],
            },
        ),
    ]
